// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvRaspored.Models;

namespace TvRaspored.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201009164146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TvRaspored.Models.Emisija", b =>
                {
                    b.Property<int>("EmisijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("emisija_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumVrijemePocetka")
                        .HasColumnName("datum_vrijeme_pocetka")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("DatumVrijemeZavrsetka")
                        .HasColumnName("datum_vrijeme_zavrsetka")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnName("naziv")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnName("opis")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int>("TvpostajaId")
                        .HasColumnName("tvpostaja_id")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnName("zanr_id")
                        .HasColumnType("int");

                    b.HasKey("EmisijaId");

                    b.HasIndex("TvpostajaId")
                        .HasName("fk_emisija_tvpostaja1_idx");

                    b.HasIndex("ZanrId")
                        .HasName("fk_emisija_zanr1_idx");

                    b.ToTable("emisija");
                });

            modelBuilder.Entity("TvRaspored.Models.Korisnik", b =>
                {
                    b.Property<int>("KorisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("korisnik_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DatumPrijave")
                        .HasColumnName("datum_prijave")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnName("ime")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasColumnName("korisnicko_ime")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Lozinka")
                        .HasColumnName("lozinka")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnName("prezime")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Slika")
                        .HasColumnName("slika")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("TipId")
                        .HasColumnName("tip_id")
                        .HasColumnType("int");

                    b.HasKey("KorisnikId");

                    b.HasIndex("TipId");

                    b.ToTable("korisnik");
                });

            modelBuilder.Entity("TvRaspored.Models.Pretplata", b =>
                {
                    b.Property<int>("EmisijaId")
                        .HasColumnName("emisija_id")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnName("korisnik_id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.HasIndex("EmisijaId")
                        .HasName("fk_korisnik_has_emisija_emisija1_idx");

                    b.HasIndex("KorisnikId")
                        .HasName("fk_korisnik_has_emisija_korisnik1_idx");

                    b.ToTable("pretplata");
                });

            modelBuilder.Entity("TvRaspored.Models.TipKorisnika", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tip_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnName("naziv")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("TipId")
                        .HasName("pk_tip_korisnika");

                    b.ToTable("tip_korisnika");
                });

            modelBuilder.Entity("TvRaspored.Models.Tvpostaja", b =>
                {
                    b.Property<int>("TvpostajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tvpostaja_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ModeratorId")
                        .HasColumnName("moderator_id")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnName("naziv")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("TvpostajaId");

                    b.HasIndex("ModeratorId")
                        .HasName("fk_tvpostaja_korisnik1_idx");

                    b.ToTable("tvpostaja");
                });

            modelBuilder.Entity("TvRaspored.Models.Zanr", b =>
                {
                    b.Property<int>("ZanrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zanr_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnName("naziv")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ZanrId");

                    b.ToTable("zanr");
                });

            modelBuilder.Entity("TvRaspored.Models.Emisija", b =>
                {
                    b.HasOne("TvRaspored.Models.Tvpostaja", "Tvpostaja")
                        .WithMany("Emisija")
                        .HasForeignKey("TvpostajaId")
                        .HasConstraintName("fk_emisija_tvpostaja1")
                        .IsRequired();

                    b.HasOne("TvRaspored.Models.Zanr", "Zanr")
                        .WithMany("Emisija")
                        .HasForeignKey("ZanrId")
                        .HasConstraintName("fk_emisija_zanr1")
                        .IsRequired();
                });

            modelBuilder.Entity("TvRaspored.Models.Korisnik", b =>
                {
                    b.HasOne("TvRaspored.Models.TipKorisnika", "Tip")
                        .WithMany("Korisnik")
                        .HasForeignKey("TipId")
                        .HasConstraintName("fk_korisnik_tip_korisnika")
                        .IsRequired();
                });

            modelBuilder.Entity("TvRaspored.Models.Pretplata", b =>
                {
                    b.HasOne("TvRaspored.Models.Emisija", "Emisija")
                        .WithMany()
                        .HasForeignKey("EmisijaId")
                        .HasConstraintName("fk_korisnik_has_emisija_emisija1")
                        .IsRequired();

                    b.HasOne("TvRaspored.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("fk_korisnik_has_emisija_korisnik1")
                        .IsRequired();
                });

            modelBuilder.Entity("TvRaspored.Models.Tvpostaja", b =>
                {
                    b.HasOne("TvRaspored.Models.Korisnik", "Moderator")
                        .WithMany("Tvpostaja")
                        .HasForeignKey("ModeratorId")
                        .HasConstraintName("fk_tvpostaja_korisnik1")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
